[icedos.applications]
aagl = false
android-tools = false
brave = false
celluloid = false
clamav = false
nvchad = true
php = false
pitivi = false
rust = false
solaar = true
sunshine = false
suyu = false
yazi = false

[icedos.applications.codium]
enable = true
extensions = [
  "codezombiech.gitignore",
  "dbaeumer.vscode-eslint",
  "donjayamanne.githistory",
  "eamodio.gitlens",
  "editorconfig.editorconfig",
  "esbenp.prettier-vscode",
  "formulahendry.auto-close-tag",
  "formulahendry.code-runner",
  "gruntfuggly.todo-tree",
  "jnoortheen.nix-ide",
  "markwylde.vscode-filesize",
  "mblode.twig-language-2",
  "ms-vscode.references-view",
  "nico-castell.linux-desktop-file",
  "paragdiwan.gitpatch",
  "pkief.material-icon-theme",
  "tamasfe.even-better-toml",
  "timonwong.shellcheck",
  "zhuangtongfa.material-theme",
  "ziyasal.vscode-open-in-github",
]
zoomLevel = 0

[icedos.applications.mangohud]
enable = true
maxFpsLimit = 165 # Use 0 for unlimited

[icedos.applications.kitty]
enable = true
hideDecorations = true # Hide top bar

[icedos.applications.librewolf]
enable = true
default = true
overrides = false
privacy = false

[icedos.applications.librewolf.pwas]
enable = true
sites = [
  "https://discord.com/app"
]

[icedos.applications.steam]
enable = true
beta = true
downloadsWorkaround = true

[icedos.applications.steam.session]
enable = false
useValveKernel = false
user = "orfous"

[icedos.applications.steam.session.autoStart]
enable = false
desktopSession = "hyprland"

[icedos.applications.tailscale]
enable = true
enableTrayscale = true

[icedos.applications.valent]
enable = true
deviceId = "901524a4_c7c0_407e_9903_431abce54131"

[icedos.applications.zed]
enable = true
ollamaSupport = false

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # system, dark, light

[icedos.applications.zen-browser]
enable = true
default = false
overrides = true
privacy = true

[icedos.applications.zen-browser.pwas]
enable = false
sites = [
  "https://app.tuta.com",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com/",
  "https://web.skype.com/",
]

[icedos.bootloader]
animation = false # Hides linux kernel logs and displays a loading interface based on OEM

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot"

[icedos.desktop]
gtkAccentColor = "#913A8B"

[icedos.desktop.autologin]
enable = false
user = "orfous"

[icedos.desktop.gdm]
enable = true
autoSuspend = true

[icedos.desktop.gnome]
enable = true
hotCorners = true
powerButtonAction = "interactive"
startupItems = true

# Options: 'minimize', 'maximize', 'close', 'spacer'(adds space between buttons), ':'(left-center-right separator)
titlebarLayout = "appmenu:minimize,close"

[icedos.desktop.gnome.extensions]
arcmenu = false
dashToPanel = false
gsconnect = false

[icedos.desktop.gnome.clock]
date = false # Show the month and day of the month on the clock
weekday = false # Show the day of the week on the clock

[icedos.desktop.gnome.workspaces]
dynamicWorkspaces = true
maxWorkspaces = 1 # Determines the maximum number of workspaces when dynamic workspaces are disabled

[icedos.desktop.hyprland]
enable = false
backlight = "amdgpu_bl0" # Find backlight unit using brightnessctl
gatewayVpn = true
hyprexpo = true # Activity viewer
mainMonitor = "DP-1"

[icedos.desktop.hyprland.cs2fix]
enable = false
width = 1440
height = 1080

[icedos.desktop.hyprland.lock]
secondsToLowerBrightness = 60
cpuUsageThreshold = 60 # CPU usage to inhibit lock in percentage
diskUsageThreshold = 10 # Disk usage to inhibit lock in MB/s
networkUsageThreshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.hardware]
bluetooth = true
mounts = true # Set to false if hardware/mounts.nix is not correctly configured

[icedos.hardware.btrfs.compression]
enable = true
mounts = true # Use btrfs compression for mounted drives
root = true # Use btrfs compression for / (root)

[icedos.hardware.cpus]
intel = false

[icedos.hardware.cpus.amd]
enable = true

[icedos.hardware.cpus.amd.undervolt]
enable = true
value = "-p 0 -v 3C -f A0" # Pstate 0, 1.175 voltage, 4000 clock speed

[icedos.hardware.devices]
laptop = false
steamdeck = false

[icedos.hardware.drivers]
xpadneo = false # Xbox gamepad bluetooth driver (supports various xinput controllers)

[icedos.hardware.devices.server]
enable = false
dns = "9.9.9.9"
gateway = "192.168.1.1"
interface = "eno1"
ip = "192.168.1.3"

[icedos.hardware.gpus.amd]
enable = false
rocm = true

[icedos.hardware.gpus.nvidia]
enable = true
beta = true
cuda = false

[icedos.hardware.gpus.nvidia.powerLimit]
enable = false
value = 242

[[icedos.hardware.monitors]]
name = "DP-0"
resolution = "2560x1440"
refreshRate = 165
position = "0x0"
scaling = 1
rotation = 0

[[icedos.hardware.monitors]]
name = "HDMI-0"
resolution = "1920x1080"
refreshRate = 60
position = "2560x360"
scaling = 1
rotation = 0

[icedos.hardware.networking]
hostname = "desktop"
hosts = false
ipv6 = false

[icedos.system]
home = "/home"
swappiness = 1
version = "23.11" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.channels]
master = false
nixos-unstable-small = false
staging = false
staging-next = false

[icedos.system.config]
version = "1.0.0"

[icedos.system.generations]
bootEntries = 10

[icedos.system.generations.garbageCollect]
automatic = false
days = 0 # Number of days before a generation can be deleted
generations = 10 # Number of generations that will always be kept
interval = "7d" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.orfous]
description = "Orfous"
type = "main" # (main, work, server)

[icedos.system.users.orfous.applications.codium]
autoSave = "off" # off, afterDelay, onFocusChange, onWindowChange
formatOnSave = true
formatOnPaste = true

[icedos.system.users.orfous.applications.git]
username = "Orfous"
email = "orfous29@gmail.com"

[icedos.system.users.orfous.applications.nvchad]
formatOnSave = true

[icedos.system.users.orfous.desktop.gnome.pinnedApps.arcmenu]
enable = false
list = ["codiumIDE.desktop", "codium.desktop", "mullvad-vpn.desktop"]

# Set pinned apps for gnome shell (will be used by dash-to-panel if enabled)
[icedos.system.users.orfous.desktop.gnome.pinnedApps.shell]
enable = false
list = [
  "steam.desktop",
  "webcord.desktop",
  "signal-desktop.desktop",
  "librewolf.desktop",
]

[icedos.system.users.orfous.desktop.idle.lock]
enable = true
seconds = 600

[icedos.system.users.orfous.desktop.idle.disableMonitors]
enable = true
seconds = 300

[icedos.system.users.orfous.desktop.idle.suspend]
enable = true
seconds = 900

[icedos.system.virtualisation]
libvirtd = true # A daemon that manages virtual machines
waydroid = true # Android container

[icedos.system.virtualisation.containerManager]
enable = true
usePodman = true
requireSudoForDocker = true # CAUTION: Disabling this gives every user root priviledges!
